############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Overview"
pageRef = "/overview"
weight = 2

[[main]]
name = "Content"
pageRef = "/authors"
weight = 3

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 4

