############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Portrait"
pageRef = "/about"
weight = 2

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 3

