############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Story"
pageRef = "/story"
weight = 2

[[main]]
name = "Characters"
pageRef = "/characters"
weight = 3

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 4

